### ISSUE TITLE
No longer works in OSX Monterey due to system permissions

### ISSUE THREAD

**Issue by pedropombeiro** [huserben/walkingpad#7]
When running scan.py, I saw that Python crashed due to this:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [27194]
Path:                  /usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.9.7 (3.9.7)
Code Type:             X86-64 (Native)
Parent Process:        zsh [1032]
Responsible:           iTerm2 [534]
User ID:               501

Date/Time:             2021-11-01 11:20:27.6048 +0100
OS Version:            macOS 12.0.1 (21A559)
Report Version:        12
Bridge OS Version:     6.0 (19P548)

System Integrity Protection: enabled

Crashed Thread:        2  Dispatch queue: com.apple.root.default-qos

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace TCC, Code 0 
This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothAlwaysUsageDescription key with a string value explaining to the user how the app uses this data.
```

Not sure which Info.plist that would be...

**Comment by huserben** [comment]
Hi @pedropombeiro 

oh ok, I've never seen this before, but also I do not own any apple device.
I never heard about Info.plist either - it seems to be apple specific as far as I can tell though...not sure what to do about this to be honest 😞

**Comment by pedropombeiro** [comment]
Hopefully someone who is more knowledgeable with deploying Python apps on mac will run into the same issue and be able to fix this.

**Comment by pedropombeiro** [comment]
I'll close this, it seems that the problem is already captured upstream: https://github.com/hbldh/bleak/issues/635

**Comment by pedropombeiro** [comment]
The upstream issue has been fixed in https://github.com/ph4r05/ph4-walkingpad/issues/3 and verified to be working, however a simple upgrade doesn't fix things for this library 🤔 

I can run a scan successfully, and update `config.yaml` with the ID, but restserver.py isn't able to connect to the device.

**Comment by huserben** [comment]
This is strange, as I don't think there is anything special with how the ph4 library is used (as far as I remember). I guess the API itself did not change?

**Comment by pedropombeiro** [comment]
Yeah, I think the major change was internal (passing the expected service IDs when connecting to the device).

**Comment by huserben** [comment]
Ok. Any idea what could be the problem then? Or how we can try to improve? :-)

**Comment by pedropombeiro** [comment]
Other than documenting that this project is not supported on Monterey, no.

**Comment by huserben** [comment]
Ok I will update the Readme with this information. In case you would have a clue on how it could be fixed let me know and I'll try to integrate it.

**Comment by darnfish** [comment]
I fixed this by adding my terminal, `iTerm.app`, to Bluetooth permissions in System Preferences:

<img width="493" alt="Screenshot 2023-01-07 at 9 15 57 AM" src="https://user-images.githubusercontent.com/8293444/211155138-7c8c2463-6a9f-4806-a304-a7b5f32879bc.png">
